# k8s/service-prod.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
  - port: 80
    targetPort: 80